name: EKS Cluster Destroy

on:
  workflow_dispatch:  # Manual trigger from GitHub UI
  push:
    branches:
      - master  # Optional: Trigger destroy on push to the master branch

jobs:
  destroy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Configure AWS credentials (replace with your secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Replace with your region

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Validate Terraform
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Terraform Plan (Optional, to preview what will be destroyed)
      - name: Terraform Plan
        run: terraform plan -destroy -out=tfdestroy.plan

      # Step 7: Apply Terraform Destroy
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
