name: Terraform Destroy

on:
  workflow_dispatch:
    # Allows manual trigger
  push:
    branches:
      - main # Adjust branch if necessary

jobs:
  destroy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0 # Change to the version you're using

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (optional, preview destroy)
        run: terraform plan -destroy -out=destroy.plan

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Store AWS credentials in GitHub secrets
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'  # Modify as needed
