name: EKS Cluster Setup

on:
  push:
    branches:
      - master  # Trigger workflow on push to the master branch
  pull_request:
  workflow_dispatch:  # Manually trigger from GitHub UI

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Configure AWS credentials (replace with your secrets)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Replace with your region

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Validate Terraform
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Decide whether to apply or destroy based on the event
      - name: Terraform Apply or Destroy
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            terraform apply -auto-approve
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            terraform destroy -auto-approve
          fi
